version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  express-app:
    image: tranngocphuochoang/practice_docker:1.0
    ports:
      - 5000:3000
    environment:
      PORT: 3000
      MONGO_DB_URI: mongodb+srv://phkane732002:OOIXmNoLOjQ50Fkj@practice.f9ubcid.mongodb.net/?retryWrites=true&w=majority&appName=practice
    depends_on:
      - mongo
volumes:
  mongo-data:
